// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuxPDe-n-NTVeV7hSaiLtgz55eLz5_Nn4',
    appId: '1:26137712652:web:0f9f028513e997c578f629',
    messagingSenderId: '26137712652',
    projectId: 'athlete-app-e777d',
    authDomain: 'athlete-app-e777d.firebaseapp.com',
    storageBucket: 'athlete-app-e777d.firebasestorage.app',
    measurementId: 'G-JLZD26M34Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAopz85pcZtdDUDR-ZA0sVVC7MQ3vo0DPU',
    appId: '1:26137712652:android:2d22b5ed9cc68af978f629',
    messagingSenderId: '26137712652',
    projectId: 'athlete-app-e777d',
    storageBucket: 'athlete-app-e777d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBURbNz3H5RKrSqvc1QxsiaPT4orttFNNc',
    appId: '1:26137712652:ios:dc10e1dfc560c81578f629',
    messagingSenderId: '26137712652',
    projectId: 'athlete-app-e777d',
    storageBucket: 'athlete-app-e777d.firebasestorage.app',
    iosClientId: '26137712652-irqcl83cau38nkc7jm6h5lkaiqv65n38.apps.googleusercontent.com',
    iosBundleId: 'com.example.athleteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBURbNz3H5RKrSqvc1QxsiaPT4orttFNNc',
    appId: '1:26137712652:ios:dc10e1dfc560c81578f629',
    messagingSenderId: '26137712652',
    projectId: 'athlete-app-e777d',
    storageBucket: 'athlete-app-e777d.firebasestorage.app',
    iosClientId: '26137712652-irqcl83cau38nkc7jm6h5lkaiqv65n38.apps.googleusercontent.com',
    iosBundleId: 'com.example.athleteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuxPDe-n-NTVeV7hSaiLtgz55eLz5_Nn4',
    appId: '1:26137712652:web:c0f62a17567d2e9378f629',
    messagingSenderId: '26137712652',
    projectId: 'athlete-app-e777d',
    authDomain: 'athlete-app-e777d.firebaseapp.com',
    storageBucket: 'athlete-app-e777d.firebasestorage.app',
    measurementId: 'G-26WWEYLZHP',
  );
}
